[build]
  # Build settings for Quiz App
  publish = "."
  command = "echo 'No build process required - static files ready'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  # Apply headers to all files
  for = "/*"
  
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Special headers for HTML files
  for = "/*.html"
  
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Headers for CSS and JS files
  for = "/*.css"
  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules (if needed)
[[redirects]]
  from = "/quiz"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/game"
  to = "/index.html"
  status = 200

# 404 redirect to main page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404